apiVersion: v1
kind: PersistentVolume
metadata:
  name: spring-pv

spec:
  capacity:
    storage: 2Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: /data/spring-petclinic

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-pvc
  namespace: dev

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi