
apiVersion: v1
kind: ConfigMap 
metadata: 
  name: spring-config
  namespace: dev
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.config.springProfile }}"
  APP_NAME: "spring-pet-clinic"

---

apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: dev

type: Opaque

data:
  DB_USERNAME: {{ .Values.secret.dbUser | b64enc}}
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc}}

---


  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: dev
  labels:
    app: spring-petclinic
spec:
  minReadySeconds: 5
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: spring-petclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: my-pod
      labels:
        app: spring-petclinic
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: spring-petclinic
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag}}"

          imagePullPolicy: {{ .Values.image.pullPolicy}}

          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-config

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: DB_PASSWORD

          resources:
            {{- toYaml .Values.resources | nindent 10 }}

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15

          volumeMounts:
            - name: app-storage
              mountPath: /logs

      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: spring-pvc
